### ISSUE TITLE
TypeError: convert_file() missing 1 required positional argument: 'fail_on_unsupported_jinja' on pixi exec feedrattler

### ISSUE THREAD

**Issue by traversaro** [hadim/feedrattler#53]
See:

~~~
traversaro@IITBMP014LW012:~$ pixi exec feedrattler osqp-eigen-feedstock
[11:53:06] INFO     🔍 Detected git_protocol from gh CLI: https                                                                                                                                                                                                  utils.py:159
           INFO     🚀 Start converting conda-forge/osqp-eigen-feedstock to v1 recipe using GH user 'traversaro'                                                                                                                                                convert.py:45
           INFO     📦 feedstock_name=osqp-eigen-feedstock                                                                                                                                                                                                      convert.py:48
           INFO     👤 github_username=traversaro                                                                                                                                                                                                               convert.py:49
           INFO     🔧 use_pixi=True                                                                                                                                                                                                                            convert.py:50
[11:53:07] INFO     🔍 Checking if osqp-eigen-feedstock is already a v1 feedstock with `recipe/recipe.yaml`                                                                                                                                                     convert.py:57
[11:53:08] INFO     ✅ osqp-eigen-feedstock is not a v1 feedstock.                                                                                                                                                                                              convert.py:70
           INFO     🔄 Cloning https://github.com/conda-forge/osqp-eigen-feedstock.git to /tmp/tmpmmek2tfp/osqp-eigen-feedstock                                                                                                                                 convert.py:90
           INFO     🔄 Converting `meta.yaml` to `recipe.yaml`                                                                                                                                                                                                 convert.py:104
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ /home/traversaro/.cache/rattler/cache/cached-envs-v0/feedrattler-cb1b49fb5a9c20e3/lib/python3.13/site-packages/feedrattler/cli.py:135 in main                                                                                                                             │
│                                                                                                                                                                                                                                                                           │
│   132 │   if clone_type == CloneType.auto:                                                     ╭───────────────────────────────────── locals ─────────────────────────────────────╮                                                                                       │
│   133 │   │   clone_type = auto_detect_clone_type(github_username)                             │                 branch_name = 'convert_feedstock_to_v1_recipe_format'            │                                                                                       │
│   134 │                                                                                        │                  clone_type = <CloneType.https: 'https'>                         │                                                                                       │
│ ❱ 135 │   convert_feedstock_to_v1(                                                             │                      dotenv = None                                               │                                                                                       │
│   136 │   │   gh=gh,                                                                           │                    draft_pr = True                                               │                                                                                       │
│   137 │   │   feedstock_name=feedstock_name,                                                   │        enable_rerender_logs = False                                              │                                                                                       │
│   138 │   │   github_username=github_username,                                                 │              feedstock_name = 'osqp-eigen-feedstock'                             │                                                                                       │
│                                                                                                │                      FORMAT = '%(message)s'                                      │                                                                                       │
│                                                                                                │                          gh = <github.MainClass.Github object at 0x74cf11c9d160> │                                                                                       │
│                                                                                                │                     git_rev = None                                               │                                                                                       │
│                                                                                                │             github_username = 'traversaro'                                       │                                                                                       │
│                                                                                                │         github_username_api = 'traversaro'                                       │                                                                                       │
│                                                                                                │             local_clone_dir = None                                               │                                                                                       │
│                                                                                                │ local_clone_dir_force_erase = False                                              │                                                                                       │
│                                                                                                │                   log_level = 'INFO'                                             │                                                                                       │
│                                                                                                │                    rerender = True                                               │                                                                                       │
│                                                                                                │                    use_pixi = True                                               │                                                                                       │
│                                                                                                │                     version = None                                               │                                                                                       │
│                                                                                                ╰──────────────────────────────────────────────────────────────────────────────────╯                                                                                       │
│                                                                                                                                                                                                                                                                           │
│ /home/traversaro/.cache/rattler/cache/cached-envs-v0/feedrattler-cb1b49fb5a9c20e3/lib/python3.13/site-packages/feedrattler/convert.py:107 in convert_feedstock_to_v1                                                                                                      │
│                                                                                                                                                                                                                                                                           │
│   104 │   logging.info("🔄 Converting `meta.yaml` to `recipe.yaml`")                           ╭────────────────────────────────────────────── locals ───────────────────────────────────────────────╮                                                                    │
│   105 │   meta_yaml_path = repo_dir_temp / "recipe" / "meta.yaml"                              │                 branch_name = 'convert_feedstock_to_v1_recipe_format'                               │                                                                    │
│   106 │   recipe_yaml_path = repo_dir_temp / "recipe" / "recipe.yaml"                          │                  clone_type = <CloneType.https: 'https'>                                            │                                                                    │
│ ❱ 107 │   result = convert_file(meta_yaml_path, output=recipe_yaml_path, print_output=False, d │                 do_rerender = True                                                                  │                                                                    │
│   108 │                                                                                        │                    draft_pr = True                                                                  │                                                                    │
│   109 │   if result.code == ExitCode.RENDER_WARNINGS:                                          │        enable_rerender_logs = False                                                                 │                                                                    │
│   110 │   │   warning_msg = f"❗ Warning while converting {meta_yaml_path} to {recipe_yaml_pat │              feedstock_name = 'osqp-eigen-feedstock'                                                │                                                                    │
│                                                                                                │                          gh = <github.MainClass.Github object at 0x74cf11c9d160>                    │                                                                    │
│                                                                                                │                     gh_repo = Repository(full_name="conda-forge/osqp-eigen-feedstock")              │                                                                    │
│                                                                                                │                    git_repo = <git.repo.base.Repo '/tmp/tmpmmek2tfp/osqp-eigen-feedstock/.git'>     │                                                                    │
│                                                                                                │                     git_rev = None                                                                  │                                                                    │
│                                                                                                │             github_username = 'traversaro'                                                          │                                                                    │
│                                                                                                │             is_v1_feedstock = False                                                                 │                                                                    │
│                                                                                                │             local_clone_dir = None                                                                  │                                                                    │
│                                                                                                │ local_clone_dir_force_erase = False                                                                 │                                                                    │
│                                                                                                │              meta_yaml_path = PosixPath('/tmp/tmpmmek2tfp/osqp-eigen-feedstock/recipe/meta.yaml')   │                                                                    │
│                                                                                                │                  new_branch = <git.Head "refs/heads/convert_feedstock_to_v1_recipe_format">         │                                                                    │
│                                                                                                │                         org = Organization(login="conda-forge")                                     │                                                                    │
│                                                                                                │            recipe_yaml_path = PosixPath('/tmp/tmpmmek2tfp/osqp-eigen-feedstock/recipe/recipe.yaml') │                                                                    │
│                                                                                                │               repo_dir_temp = PosixPath('/tmp/tmpmmek2tfp/osqp-eigen-feedstock')                    │                                                                    │
│                                                                                                │        repo_dir_temp_parent = PosixPath('/tmp/tmpmmek2tfp')                                         │                                                                    │
│                                                                                                │                    use_pixi = True                                                                  │                                                                    │
│                                                                                                ╰─────────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: convert_file() missing 1 required positional argument: 'fail_on_unsupported_jinja'
~~~

probably a regression due to https://github.com/conda/conda-recipe-manager/pull/444 .
